remote_theme: pmarsceill/just-the-docs

layout: default
title: Home
nav_order: 1

layout: default
title: OMS
parent: Home
nav_order: 2

layout: default
title: PMS
parent: Home
nav_order: 2

layout: default
title: Order
parent: Home
nav_order: 2
